# Generated by Django 2.2.1 on 2019-05-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembawa',
            name='descpembawa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pembawa',
            name='kdpenyakit',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
