# Generated by Django 2.2.1 on 2019-05-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190516_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembawa',
            name='kdpenyakit',
            field=models.IntegerField(null=True, verbose_name=20),
        ),
    ]
